version: '3.2'

networks:
  frontend:
    external:
      name: mynet 
  backend: 
  
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/management/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      labels:
        #traefik.port: "9090"
        #traefik.frontend.rule: "Host:prometheus.myhost.com"
        # traefik.frontend.auth.basic.usersFile: /path/.htpasswd   
        #traefik.frontend.auth.basic.users: "admin:$$axxxxxxxxxxxxxxxxxxxxxxxxx"
        #traefik.docker.network: "mynet" 
      placement:
        constraints:
          - node.role == manager
    networks:
      - frontend
      - backend     

  manager-ccc:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == ccc
    networks:
      - backend
      
 manager-pensiuncore:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == pensiuncore
    networks:
      - backend
  
 docker-manager-ccc:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
         # Hostname of the first manager node!
          - node.hostname == ccc
    networks:
      - backend
      
 docker-manager-pensiuncore:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
         # Hostname of the first manager node!
          - node.hostname == pensiuncore
    networks:
      - backend

 grafana:
    image: grafana/grafana
    #environment:
    #  GF_SMTP_ENABLED: "true"
    #  GF_SMTP_HOST: "mailgateway:25"
    #  GF_SMTP_FROM_ADDRESS: "alert@myhost.com"
    volumes: 
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    deploy:
#      labels:
#        traefik.port: "3000"
#        traefik.frontend.rule: "Host:grafana.myhost.com"
#        traefik.docker.network: "mynet" 
      placement:
        constraints:
          - node.role == manager
    networks:
      - frontend
      - backend

volumes:
  grafana-data:



