version: '3.7'
  
services:
#   prometheus:
#     image: prom/prometheus:latest
#     hostname: "{{.Node.Hostname}}"
#     networks:
#       - appnet
#     environment:
#      - SET_CONTAINER_TIMEZONE=true
#      - CONTAINER_TIMEZONE=Asia/Jakarta
#     volumes:
#       - $PWD/management/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#       - prometheus:/prometheus
#     ports:
#       - "9090:9090"
#     deploy:
#       restart_policy:
#         condition: on-failure
#       placement:
#         constraints:
#           - node.hostname == pensiuncore  
      
  node-exporter:
    image: prom/node-exporter:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - appnet
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Jakarta
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
      
  cadvisor:
    image: google/cadvisor:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - appnet
    environment:
     - SET_CONTAINER_TIMEZONE=true
     - CONTAINER_TIMEZONE=Asia/Jakarta
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      restart_policy:
        condition: on-failure
      mode: global

  grafana:
    image: grafana/grafana:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - appnet
    environment:
     - SET_CONTAINER_TIMEZONE=true
     - CONTAINER_TIMEZONE=Asia/Jakarta
    volumes: 
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == pensiuncore
        
networks:
  appnet:
    driver: overlay
    external: true  
    
volumes:
  grafana-data:
  prometheus:
