# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

#     - job_name: nodexporter
#       scheme: http
#       metrics_path: /metrics
#       scrape_interval: 15s
#       dns_sd_configs:
#         - names:
#             - "tasks.nodexporter"
#           type: 'A'
#           port: 9100
#       tls_config:
#         insecure_skip_verify: true
          
#     - job_name: cadvisor
#       scheme: http
#       metrics_path: /metrics
#       scrape_interval: 15s
#       dns_sd_configs:
#         - names:
#             - "tasks.cadvisor"
#           type: 'A'
#           port: 8080
#       tls_config:
#         insecure_skip_verify: true
  - job_name: 'ccc-exporter'
    scheme: http
    static_configs:
      - targets: ['52.221.198.120:9100']
    tls_config:
      insecure_skip_verify: true
      
  - job_name: 'ccc-cadvisor'
    scheme: http
    static_configs:
      - targets: ['52.221.198.120:8080']
    tls_config:
      insecure_skip_verify: true
