version: '3.2'

services:
  proxy:
     image: traefik:latest
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - $PWD/management/traefik/traefik.toml:/etc/traefik/traefik.toml
       - acme:/etc/traefik/acme
     ports:
       - 80:80
       - 443:443
       - 8088:8080
     deploy:
       placement:
         constraints:
           - node.hostname == proxy

volumes:
  acme:
 
